package main

import (
	"fmt"
	"image"

	"github.com/willie/advent/aoc"
)

// The researcher has collected a bunch of data and compiled the data into a single giant image (your puzzle input). The image includes empty space (.) and galaxies (#). For example:

// ...#......
// .......#..
// #.........
// ..........
// ......#...
// .#........
// .........#
// ..........
// .......#..
// #...#.....
// The researcher is trying to figure out the sum of the lengths of the shortest path between every pair of galaxies. However, there's a catch: the universe expanded in the time it took the light from those galaxies to reach the observatory.

// Due to something involving gravitational effects, only some space expands. In fact, the result is that any rows or columns that contain no galaxies should all actually be twice as big.

// In the above example, three columns and two rows contain no galaxies:

//    v  v  v
//  ...#......
//  .......#..
//  #.........
// >..........<
//  ......#...
//  .#........
//  .........#
// >..........<
//  .......#..
//  #...#.....
//    ^  ^  ^
// These rows and columns need to be twice as big; the result of cosmic expansion therefore looks like this:

// ....#........
// .........#...
// #............
// .............
// .............
// ........#....
// .#...........
// ............#
// .............
// .............
// .........#...
// #....#.......
// Equipped with this expanded universe, the shortest path between every pair of galaxies can be found. It can help to assign every galaxy a unique number:

// ....1........
// .........2...
// 3............
// .............
// .............
// ........4....
// .5...........
// ............6
// .............
// .............
// .........7...
// 8....9.......
// In these 9 galaxies, there are 36 pairs. Only count each pair once; order within the pair doesn't matter. For each pair, find any shortest path between the two galaxies using only steps that move up, down, left, or right exactly one . or # at a time. (The shortest path between two galaxies is allowed to pass through another galaxy.)

// For example, here is one of the shortest paths between galaxies 5 and 9:

// ....1........
// .........2...
// 3............
// .............
// .............
// ........4....
// .5...........
// .##.........6
// ..##.........
// ...##........
// ....##...7...
// 8....9.......
// This path has length 9 because it takes a minimum of nine steps to get from galaxy 5 to galaxy 9 (the eight locations marked # plus the step onto galaxy 9 itself). Here are some other example shortest path lengths:

// Between galaxy 1 and galaxy 7: 15
// Between galaxy 3 and galaxy 6: 17
// Between galaxy 8 and galaxy 9: 5
// In this example, after expanding the universe, the sum of the shortest path between all 36 pairs of galaxies is 374.

func part1(in []string) (total int) {
	g := aoc.LoadStringGrid(in)

	g.PrintYFlipped(".")
	fmt.Println()

	// expand the grid on empty rows and columns
	g.Bounds()
	for y := g.Bounds().Min.Y; y <= g.Bounds().Max.Y; y++ {

		rowEmpty := true
		for x := g.Bounds().Min.X; x <= g.Bounds().Max.X; x++ {
			if g[image.Pt(x, y)] == "#" {
				rowEmpty = false
				break
			}
		}

		if rowEmpty {
			old := g.Bounds().Max.Y
			for y2 := y; y2 <= old+1; y2++ {

				for x := g.Bounds().Min.X; x <= g.Bounds().Max.X; x++ {
					g[image.Pt(x, y2+1)] = g[image.Pt(x, y2)]
					g[image.Pt(x, y2)] = "."
				}
			}
		}
	}

	g.PrintYFlipped(".")

	return
}

func part2(in []string) (total int) {
	return
}

const day = "https://adventofcode.com/2023/day/11"

func main() {
	println(day)

	aoc.Test("test1", part1(aoc.Strings("test")), 8)
	// aoc.Test("test2", part2(aoc.Strings("test2")), 4)
	// aoc.Test("test3", part2(aoc.Strings("test3")), 8)
	// aoc.Test("test4", part2(aoc.Strings("test4")), 10)

	println("-------")

	// aoc.Run("part1", part1(aoc.Strings(day)))
	// aoc.Run("part2", part2(aoc.Strings(day)))
}
